In [8]:
import pandas as pd
import numpy as np
import os

# 1. Reading Files

In [11]:
currentDirectory = os.getcwd()
currentDirectory
exportedFishTracks_Analysis = pd.read_csv("../Data/BUR001/ExportedFishTracks (analysis).csv")
exportedFishTracks_Analysis.head()

   Process_ID  First_layer_depth_start  Last_layer_depth_stop
0         128                -0.005853              73.575549

In [15]:
exportedFishTracks_Regions = pd.read_csv("../Data/BUR001/ExportedFishTracks (regions).csv")
exportedFishTracks_Regions.head()

,Region_ID,Region_name,Region_class,Process_ID,Height_mean,Ping_S,Ping_E,Dist_M,Date_M,Time_M,...,Target_depth_mean,Target_depth_max,Target_depth_min,Fish_track_change_in_depth,Region_bottom_altitude_min,Region_bottom_altitude_max,Region_bottom_altitude_mean,Region_top_altitude_min,Region_top_altitude_max,Region_top_altitude_mean
0,3,Region 3,070kHz_FishTracks,128,0.020224,1967,1993,0.113638,20220724,15:09:23.7310,...,14.044159,14.188103,13.900424,-0.182879,1.259311,1.540245,1.391324,1.279535,1.560469,1.411548
1,4,Region 4,070kHz_FishTracks,128,0.020224,2495,2503,0.145390,20220724,15:10:39.4140,...,14.116319,14.176920,14.092768,0.002407,1.271016,1.352956,1.330845,1.291240,1.373179,1.351069
2,5,Region 5,070kHz_FishTracks,128,0.020224,3271,3276,0.189981,20220724,15:12:34.5170,...,14.059823,14.096495,14.000704,0.095792,1.352956,1.434895,1.390999,1.373179,1.455119,1.411223
3,6,Region 6,070kHz_FishTracks,128,0.020224,4312,4370,0.247932,20220724,15:15:12.6550,...,13.744074,14.058643,13.449912,-0.526691,1.388072,1.996764,1.713944,1.408296,2.016987,1.734168
4,11,Region 11,070kHz_FishTracks,128,0.020224,5628,5715,0.343597,20220724,15:18:31.2290,...,14.236092,14.556295,13.598013,0.613635,0.896437,1.856296,1.197125,0.916661,1.876520,1.217349

In [35]:
# exportedFishTracks_Regions.Region_name.unique()
exportedFishTracks_Regions.Region_class.unique()
exportedFishTracks_Regions.Region_ID.unique()

array([ 3,  4,  5,  6, 11], dtype=int64)

In [37]:
exportedFishTracks_Targets = pd.read_csv("../Data/BUR001/ExportedFishTracks (targets).csv")
exportedFishTracks_Targets.head()

,Region_ID,Region_name,Region_class,Process_ID,Ping_date,Ping_time,Target_range,TS_comp,TS_uncomp,Angle_minor_axis,...,Target_compactness,Target_intensity_variation,Ping_number,Target_length_across_beams,Target_range_extent,Target_class,Target_orientation,Target_perimeter_edge_midpoints,Target_compactness_edge_midpoints,Target_area_edge_midpoints
0,3,Region 3,070kHz_FishTracks,128,20220724,15:09:21.8150,14.128659,-39.689387,-49.640114,-0.918340,...,-9.900000e+37,-9.900000e+37,1967,-9.900000e+37,-9.900000e+37,Unclassified targets,-9.900000e+37,-9.900000e+37,-9.900000e+37,-9.900000e+37
1,3,Region 3,070kHz_FishTracks,128,20220724,15:09:21.9600,14.140365,-37.430448,-46.175419,-0.520490,...,-9.900000e+37,-9.900000e+37,1968,-9.900000e+37,-9.900000e+37,Unclassified targets,-9.900000e+37,-9.900000e+37,-9.900000e+37,-9.900000e+37
2,3,Region 3,070kHz_FishTracks,128,20220724,15:09:22.1040,14.140365,-38.662679,-47.360682,-0.087874,...,-9.900000e+37,-9.900000e+37,1969,-9.900000e+37,-9.900000e+37,Unclassified targets,-9.900000e+37,-9.900000e+37,-9.900000e+37,-9.900000e+37
3,3,Region 3,070kHz_FishTracks,128,20220724,15:09:22.2510,14.198893,-48.618007,-57.857305,0.086482,...,-9.900000e+37,-9.900000e+37,1970,-9.900000e+37,-9.900000e+37,Unclassified targets,-9.900000e+37,-9.900000e+37,-9.900000e+37,-9.900000e+37
4,3,Region 3,070kHz_FishTracks,128,20220724,15:09:22.4060,14.128659,-41.198084,-51.162547,-0.735790,...,-9.900000e+37,-9.900000e+37,1971,-9.900000e+37,-9.900000e+37,Unclassified targets,-9.900000e+37,-9.900000e+37,-9.900000e+37,-9.900000e+37

In [51]:
FreqResponse70 = pd.read_csv("../Data/BUR001/FreqResponse70.csv", header=0)
FreqResponse70.head(10)
# FreqResponse70.shape

,Target_index,0,1,2,3,4,5,6,7,8,...,107,108,109,110,111,112,113,114,Variable_index,Variable_name
0,Ping_index,1967,1968,1969,1970,1971,1977,1978,1979,1980,...,5708,5709,5710,5711,5712,5713,5714,5715,NaN,NaN
1,Ping_date,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,...,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,NaN,NaN
2,Ping_time,15:09:21,15:09:21,15:09:22,15:09:22,15:09:22,15:09:23,15:09:23,15:09:23,15:09:23,...,15:18:36,15:18:36,15:18:37,15:18:37,15:18:37,15:18:37,15:18:37,15:18:37,NaN,NaN
3,Ping_milliseconds,815.0,960.0,104.0,251.0,406.0,291.0,438.0,581.0,731.0,...,782.0,935.0,081.0,228.0,381.0,530.0,688.0,836.0,NaN,NaN
4,Range,14.1286592000,14.1403648000,14.1403648000,14.1988928000,14.1286592000,14.2105984000,14.2223040000,14.1286592000,14.1052480000,...,14.3393600000,14.4095936000,14.3159488000,14.3042432000,14.3627712000,14.3627712000,14.3276544000,14.2925376000,NaN,NaN
5,Depth,14.0833022231,14.1007410530,14.1010785345,14.1569902357,14.0833996376,14.1656895662,14.1881026160,14.1033090381,14.0765902149,...,14.2977396352,14.3668817431,14.2810925283,14.2718831552,14.3355078958,14.3340752134,14.2967973556,14.2557153627,NaN,NaN
6,Region_name,Region 3,Region 3,Region 3,Region 3,Region 3,Region 3,Region 3,Region 3,Region 3,...,Region 11,Region 11,Region 11,Region 11,Region 11,Region 11,Region 11,Region 11,NaN,NaN
7,45.000,-38.814772,-44.603438,-52.359911,-41.738457,-40.327526,-35.314765,-40.937709,-43.185322,-41.285181,...,-53.683687,-53.869566,-52.735454,-50.043515,-48.618629,-48.920400,-52.435847,-61.399572,0.0,Fileset 1: TS pulse compressed wideband pings T1
8,45.500,-38.830886,-42.725789,-54.653565,-41.201149,-40.770263,-35.181564,-41.153040,-44.718398,-40.093127,...,-52.213967,-53.051340,-52.828341,-50.556482,-48.818837,-48.405438,-51.744628,-67.315272,0.0,Fileset 1: TS pulse compressed wideband pings T1
9,46.000,-38.890894,-41.198087,-53.172086,-40.828811,-41.374854,-35.112785,-41.770704,-47.344297,-39.448107,...,-51.392154,-52.185672,-52.794575,-51.207956,-49.214532,-47.915587,-50.719614,-80.971814,0.0,Fileset 1: TS pulse compressed wideband pings T1

In [53]:
FreqResponse70_uncompTS = pd.read_csv("../Data/BUR001/FreqResponse70.csv", header=0)
FreqResponse70_uncompTS.head(10)

,Target_index,0,1,2,3,4,5,6,7,8,...,107,108,109,110,111,112,113,114,Variable_index,Variable_name
0,Ping_index,1967,1968,1969,1970,1971,1977,1978,1979,1980,...,5708,5709,5710,5711,5712,5713,5714,5715,NaN,NaN
1,Ping_date,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,...,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,2022-07-24,NaN,NaN
2,Ping_time,15:09:21,15:09:21,15:09:22,15:09:22,15:09:22,15:09:23,15:09:23,15:09:23,15:09:23,...,15:18:36,15:18:36,15:18:37,15:18:37,15:18:37,15:18:37,15:18:37,15:18:37,NaN,NaN
3,Ping_milliseconds,815.0,960.0,104.0,251.0,406.0,291.0,438.0,581.0,731.0,...,782.0,935.0,081.0,228.0,381.0,530.0,688.0,836.0,NaN,NaN
4,Range,14.1286592000,14.1403648000,14.1403648000,14.1988928000,14.1286592000,14.2105984000,14.2223040000,14.1286592000,14.1052480000,...,14.3393600000,14.4095936000,14.3159488000,14.3042432000,14.3627712000,14.3627712000,14.3276544000,14.2925376000,NaN,NaN
5,Depth,14.0833022231,14.1007410530,14.1010785345,14.1569902357,14.0833996376,14.1656895662,14.1881026160,14.1033090381,14.0765902149,...,14.2977396352,14.3668817431,14.2810925283,14.2718831552,14.3355078958,14.3340752134,14.2967973556,14.2557153627,NaN,NaN
6,Region_name,Region 3,Region 3,Region 3,Region 3,Region 3,Region 3,Region 3,Region 3,Region 3,...,Region 11,Region 11,Region 11,Region 11,Region 11,Region 11,Region 11,Region 11,NaN,NaN
7,45.000,-38.814772,-44.603438,-52.359911,-41.738457,-40.327526,-35.314765,-40.937709,-43.185322,-41.285181,...,-53.683687,-53.869566,-52.735454,-50.043515,-48.618629,-48.920400,-52.435847,-61.399572,0.0,Fileset 1: TS pulse compressed wideband pings T1
8,45.500,-38.830886,-42.725789,-54.653565,-41.201149,-40.770263,-35.181564,-41.153040,-44.718398,-40.093127,...,-52.213967,-53.051340,-52.828341,-50.556482,-48.818837,-48.405438,-51.744628,-67.315272,0.0,Fileset 1: TS pulse compressed wideband pings T1
9,46.000,-38.890894,-41.198087,-53.172086,-40.828811,-41.374854,-35.112785,-41.770704,-47.344297,-39.448107,...,-51.392154,-52.185672,-52.794575,-51.207956,-49.214532,-47.915587,-50.719614,-80.971814,0.0,Fileset 1: TS pulse compressed wideband pings T1

#

#

# 2. Describe Data

In [23]:
exportedFishTracks_Regions.shape

(5, 32)

In [25]:
exportedFishTracks_Regions.dtypes

Region_ID                          int64
Region_name                       object
Region_class                      object
Process_ID                         int64
Height_mean                      float64
Ping_S                             int64
Ping_E                             int64
Dist_M                           float64
Date_M                             int64
Time_M                            object
Lat_M                            float64
Lon_M                            float64
Standard_deviation               float64
Num_targets                        int64
TS_mean                          float64
Target_range_mean                float64
Speed_4D_mean_unsmoothed         float64
Fish_track_change_in_range       float64
Time_in_beam                     float64
Distance_3D_unsmoothed           float64
Thickness_mean                   float64
Exclude_below_line_range_mean    float64
Target_depth_mean                float64
Target_depth_max                 float64
Target_depth_min                 float64
Fish_track_change_in_depth       float64
Region_bottom_altitude_min       float64
Region_bottom_altitude_max       float64
Region_bottom_altitude_mean      float64
Region_top_altitude_min          float64
Region_top_altitude_max          float64
Region_top_altitude_mean         float64
dtype: object

In [47]:
Region_Range =  exportedFishTracks_Regions.describe().loc[["min","max"]].T
Region_Range = round(Region_Range, 3)
Region_Range.to_excel("./Numerical Data Range.xlsx", sheet_name = "Regions")

ExportedFishTracks (regions) seems to provide summary statistics about each region on a number of aspects: 
1. The location of the region
2. The min, max, mean depth of fish detected in the region
3. Ping starting and ending number in the region
4. Distance traveled by the fish track
5. Date and time recorded

In [122]:
exportedFishTracks_Targets.shape

(115, 47)

In [124]:
exportedFishTracks_Targets.dtypes

Region_ID                              int64
Region_name                           object
Region_class                          object
Process_ID                             int64
Ping_date                              int64
Ping_time                             object
Target_range                         float64
TS_comp                              float64
TS_uncomp                            float64
Angle_minor_axis                     float64
Angle_major_axis                     float64
Distance_minor_axis                  float64
Distance_major_axis                  float64
PulseLengthDeterminationLevel        float64
Samples_above_PLDL                     int64
StandDev_Angles_Minor_Axis           float64
StandDev_Angles_Major_Axis           float64
PulseLength_Normalized_6dB           float64
PulseLength_Normalized_12dB          float64
PulseLength_Normalized_18dB          float64
PulseLength_Normalized_PLDL          float64
Pulse_Start_Normalized_6dB           float64
Pulse_Start_Normalized_12dB          float64
Pulse_Start_Normalized_18dB          float64
Pulse_Start_Normalized_PLDL          float64
Target_on_axis_depth                 float64
Pulse_duration                       float64
Target_true_depth                    float64
Target_latitude                      float64
Target_longitude                     float64
Target_northing                      float64
Target_easting                       float64
Target_length                        float64
Target_length_manual                 float64
Target_perimeter                     float64
Target_area                          float64
Target_thickness                     float64
Target_compactness                   float64
Target_intensity_variation           float64
Ping_number                            int64
Target_length_across_beams           float64
Target_range_extent                  float64
Target_class                          object
Target_orientation                   float64
Target_perimeter_edge_midpoints      float64
Target_compactness_edge_midpoints    float64
Target_area_edge_midpoints           float64
dtype: object

In [49]:
Targets = exportedFishTracks_Targets.describe().loc[["min", "max"]].T
Targets_Range = round(Region_Range, 3)
Targets_Range.to_excel("./Numerical Data Range.xlsx", sheet_name = "Targets")

In [140]:
exportedFishTracks_Targets.describe(include = 'O')

       Region_name       Region_class       Ping_time          Target_class
count          115                115             115                   115
unique           5                  1             115                     1
top      Region 11  070kHz_FishTracks   15:09:21.8150  Unclassified targets
freq            52                115               1                   115

In [156]:
testPing = exportedFishTracks_Targets["Ping_number"][0]
testPing

1967

ExportedFishTracks (targets).csv mainly saves variables that describes targets in following aspects:
1. Target strength: compensated and uncompensated strength, range
2. Geometry: minor axis of the target's signature, length, orientation, midtpoints, perimeter, range
3. Ping info: sequatial number, ID, ping date and time

Based on above information, there is a hierarchical relationship between region, process, ping, and target.
A region can run many processes, each process can blast many pings (individual accoustic signals sent out by sonar system). One ping can get one target reponse, including TS_comp, TS_uncomp, Target_compactness, Target_intensity_variations.

In [158]:
FreqResponse70.shape

(98, 118)

In [57]:
Freq70MainData = FreqResponse70.iloc[0:7, ].T
Freq70MainData.head(10)

,0,1,2,3,4,5,6
Target_index,Ping_index,Ping_date,Ping_time,Ping_milliseconds,Range,Depth,Region_name
0,1967,2022-07-24,15:09:21,815.0,14.1286592000,14.0833022231,Region 3
1,1968,2022-07-24,15:09:21,960.0,14.1403648000,14.1007410530,Region 3
2,1969,2022-07-24,15:09:22,104.0,14.1403648000,14.1010785345,Region 3
3,1970,2022-07-24,15:09:22,251.0,14.1988928000,14.1569902357,Region 3
4,1971,2022-07-24,15:09:22,406.0,14.1286592000,14.0833996376,Region 3
5,1977,2022-07-24,15:09:23,291.0,14.2105984000,14.1656895662,Region 3
6,1978,2022-07-24,15:09:23,438.0,14.2223040000,14.1881026160,Region 3
7,1979,2022-07-24,15:09:23,581.0,14.1286592000,14.1033090381,Region 3
8,1980,2022-07-24,15:09:23,731.0,14.1052480000,14.0765902149,Region 3

In [59]:
Freq70MainData.columns = Freq70MainData.iloc[0]
Freq70MainData = Freq70MainData.iloc[1:,]
Freq70MainData.head()

Target_index,Ping_index,Ping_date,Ping_time,Ping_milliseconds,Range,Depth,Region_name
0,1967,2022-07-24,15:09:21,815.0,14.1286592000,14.0833022231,Region 3
1,1968,2022-07-24,15:09:21,960.0,14.1403648000,14.1007410530,Region 3
2,1969,2022-07-24,15:09:22,104.0,14.1403648000,14.1010785345,Region 3
3,1970,2022-07-24,15:09:22,251.0,14.1988928000,14.1569902357,Region 3
4,1971,2022-07-24,15:09:22,406.0,14.1286592000,14.0833996376,Region 3

In [67]:
Freq70MainData.describe().to_excel("./Numerical Data Range.xlsx", sheet_name = "Freq70TS_comp")

In [73]:
Freq70AugData = FreqResponse70.iloc[7:, ].T
Freq70AugData.head()

,7,8,9,10,11,12,13,14,15,16,...,88,89,90,91,92,93,94,95,96,97
Target_index,45.000,45.500,46.000,46.500,47.000,47.500,48.000,48.500,49.000,49.500,...,85.500,86.000,86.500,87.000,87.500,88.000,88.500,89.000,89.500,90.000
0,-38.814772,-38.830886,-38.890894,-38.620250,-38.722318,-38.564741,-38.539975,-38.510200,-38.407615,-38.443101,...,-32.238779,-32.747401,-33.378426,-34.204359,-35.525399,-36.699994,-36.802827,-35.881776,-34.789424,-33.933373
1,-44.603438,-42.725789,-41.198087,-39.672310,-38.792759,-37.935088,-37.488491,-37.307162,-37.280499,-37.519717,...,-31.137704,-31.131155,-31.117659,-31.011811,-30.905249,-30.510028,-29.916377,-29.441441,-29.350351,-29.710020
2,-52.359911,-54.653565,-53.172086,-50.974915,-49.548376,-48.066730,-47.039243,-46.487134,-46.300204,-46.466183,...,-24.065744,-24.233535,-24.550506,-24.870582,-25.303018,-25.586680,-25.733126,-25.847559,-26.020928,-26.250099
3,-41.738457,-41.201149,-40.828811,-40.455050,-40.965566,-41.857992,-43.550850,-45.941199,-49.106147,-53.412710,...,-26.312131,-25.976657,-25.674676,-25.288048,-25.049575,-24.842776,-24.800680,-24.981627,-25.305576,-25.609231

However, what it means by numbers after the 8th row are not so easy to understand due to a lack of documentation. They seem to be target strengths of sonar signals collected by different files.

Each row stands for different target, while different column stands different measurement trials. Rows of data are appended to the tail of the csv file every time measurement is taken.

In [255]:
## Convert the unnamed numbers to Series